name = "DEV missing gear"
description = "Clone of Herring Cove"
license = "MIT"
tags = ["blog", "company"]

[author]
    name = "jurmarko"
    homepage = "http://devmissinggear.com"

# If Porting existing theme
[original]
    author =  "jurmarko"
    repo = "http://www.github.com/jurmarko/devimissinggear"

